### ISSUE TITLE
Resolve SSH aliases

### ISSUE THREAD

**Issue by joelgriffith** [appnexus/sicksync#35]
sicksync pretty much needs "absolute" hostname URI's, which kind of stink since most folks operate under aliases to do their work.

**Comment by laggingreflex** [comment]
Is this still an issue? Or am I misunderstanding this? I'm able to just tell sicksync the actual alias that I have set up for my remote machine IP address in my `hosts` file and it's able to connect and sync just fine

**Comment by joelgriffith** [comment]
Yeah, I'm not able to reproduce this anymore as well. Recalling back that far: I think this was due to consumer misconfiguration on their machine.

Closing
