### ISSUE TITLE
Excludes aren't 100% excluded

### ISSUE THREAD

**Issue by laggingreflex** [appnexus/sicksync#47]
It seems ignored paths aren't 100% ignored. Like if I change something in the .git directory, surely it doesn't actually get uploaded but it still triggers a file change event, meaning it's still being monitored which is unnecessary. Having a huge node_modules or otherwise ignored folders cause it to take up considerable time to start up.

This can be tested by putting a console log here: [src\local\fs-helper.js](../blob/master/src/local/fs-helper.js#L38) and changing any file in one of the ignored folders, `.git/info/excludes`

**Comment by laggingreflex** [comment]
It seems the cause of this is the format of exclude patterns. `.git/**`, and `.git/**/*` don't work, but what worked for me was `**/.git`. It has something to do with how [chokidar]/[anymatch] parses and matches these ignore patterns...

[chokidar]: https://github.com/paulmillr/chokidar
[anymatch]: https://github.com/es128/anymatch

**Comment by laggingreflex** [comment]
I really would've liked if simply `.git`, or `node_modules` had worked as they do with git in `.gitignore`

Would it be desirable to augment this kind of ignore pattern parsing further? I know it already works as far as the core functionality of the project is concerned but it really shoots up the startup time for large ignored folders...

**Comment by laggingreflex** [comment]
I've made a [PR][1] to chokidar that basically prefixes `**/.git` to paths which can solve this. 

[1]: https://github.com/paulmillr/chokidar/pull/539

**Comment by joelgriffith** [comment]
@laggingreflex I think your PR satisfies this issue...

**Comment by joelgriffith** [comment]
Released in `3.0.0`, thanks!
