### ISSUE TITLE
Adding a dir that's excluded fires adddir  event

### ISSUE THREAD

**Issue by laggingreflex** [appnexus/sicksync#52]
If you have `node_modules` excluded but the dir `node_modules` hasn't actually been created yet and you've started the sync and _then_ do `npm i` which creates the `node_modules` dir, it fires the adddir event which causes the Big Rsync to be fired again. But it doesn't do anything much which is good and expected, so this probably isn't of immediate concern but still leaving this here so it might be addressed.

**Comment by joelgriffith** [comment]
Fixed in `3.0.0` thanks to your work!
